### ISSUE TITLE
LAN Scanner is missing some results

### ISSUE THREAD

**Issue by guyluz11** [ivirtex/networkarch-flutter#9]
LAN Scanner is missing some results

Using [netanalyzer](https://play.google.com/store/apps/details?id=net.techet.netanalyzerlite.an) and using [Network Scanner](https://play.google.com/store/apps/details?id=com.myprog.netscan) I am getting 16 results but while using Networkarch I am getting 13.

**Comment by ivirtex** [comment]
Hi, thanks for spotting bugs and opening all these issues, I will work on them soon.

**Comment by guyluz11** [comment]
Someone pointed out in different issue that the extra results coming from ARP TABLE.

**Comment by ivirtex** [comment]
Fixed with 2.1.2, since I am using `network_tools` package now.

**Comment by git-elliot** [comment]
> Fixed with 2.1.2, since I am using `network_tools` package now.

Glad to hear this.
